import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, Loader2, Search, Send, X } from 'lucide-react';
import { keywordRequest, type KeywordResearchItem } from '../services/keywordExplorerService';

interface Props { projectId: string; addToast: (message: string, type?: 'success' | 'error' | 'info') => void; }
const field = 'mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-emerald-500';
const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50';
const primary = `${button} !border-emerald-600 !bg-emerald-600 !text-white hover:!bg-emerald-700`;

export default function KeywordExplorer({ projectId, addToast }: Props) {
  const [items, setItems] = useState<KeywordResearchItem[]>([]);
  const [phrase, setPhrase] = useState(''); const [country, setCountry] = useState('US'); const [language, setLanguage] = useState('English'); const [context, setContext] = useState('');
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [canManage, setCanManage] = useState(false); const alive = useRef(true);
  const refresh = async () => { const data = await keywordRequest<{ items: KeywordResearchItem[]; can_manage: boolean }>(projectId, 'keyword_list'); if (alive.current) { setItems(data.items); setCanManage(data.can_manage); setError(''); } };
  useEffect(() => { alive.current = true; refresh().catch(caught => setError(caught.message)).finally(() => alive.current && setLoading(false)); return () => { alive.current = false; }; }, [projectId]);
  const perform = async (name: string, action: () => Promise<string>) => { setBusy(name); setError(''); try { addToast(await action(), 'success'); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Keyword Explorer could not finish this action.'; setError(message); addToast(message, 'error'); } finally { await refresh().catch(() => {}); if (alive.current) setBusy(''); } };
  return <div className="space-y-6">
    <section className="rounded-[2rem] border border-emerald-200 bg-emerald-50/60 p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-emerald-100 p-2 text-emerald-700"><Search size={20} /></div><div><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Keyword Explorer</p><h2 className="mt-1 text-xl font-black text-slate-900">Research a customer question before creating content</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">This is source-backed Google Search research, not Keyword Planner. It does not estimate monthly volume, competition, rankings, or keyword difficulty.</p></div></div></section>
    {error && <p role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}
    <section className="rounded-[2rem] border border-slate-200 bg-white p-6"><div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-bold text-slate-600 md:col-span-2">Keyword or customer question<input className={field} value={phrase} onChange={event => setPhrase(event.target.value)} maxLength={240} placeholder="When should I plant fall vegetable seedlings?" /></label><label className="text-xs font-bold text-slate-600">Country<input className={field} value={country} onChange={event => setCountry(event.target.value.toUpperCase())} maxLength={2} /></label><label className="text-xs font-bold text-slate-600">Language<input className={field} value={language} onChange={event => setLanguage(event.target.value)} maxLength={80} /></label><label className="text-xs font-bold text-slate-600 md:col-span-2">Optional audience or campaign context<textarea className={`${field} min-h-24`} value={context} onChange={event => setContext(event.target.value)} maxLength={2000} placeholder="Who is asking, what they need, and any useful local or seasonal context." /></label></div><button type="button" className={`${primary} mt-5`} disabled={!canManage || !phrase.trim() || Boolean(busy)} onClick={() => perform('research', async () => { await keywordRequest(projectId, 'keyword_research', { phrase, country, language, context }); setPhrase(''); setContext(''); return 'Keyword research saved with source links.'; })}>{busy === 'research' ? <Loader2 className="animate-spin" size={15} /> : <Search size={15} />}{busy === 'research' ? 'Researching…' : 'Research keyword'}</button>{!canManage && !loading && <p className="mt-3 text-xs text-amber-700">An owner, admin, or operator can manage keyword research.</p>}</section>
    {loading ? <p className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="animate-spin" size={18} />Loading keyword research…</p> : items.length === 0 ? <section className="rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No saved keyword research yet. Research a real customer question to begin.</section> : <section className="space-y-4">{items.map(item => <article key={item.id} className="space-y-4 rounded-[2rem] border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-emerald-700">{item.country} · {item.language}</p><h3 className="mt-1 text-lg font-black text-slate-900">{item.phrase}</h3></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{item.status === 'approved' ? 'In Trend Radar' : item.status}</span></div>{item.context && <p className="text-sm text-slate-600"><strong>Context:</strong> {item.context}</p>}<p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.research_summary}</p><div className="flex flex-wrap gap-3">{item.evidence.sources.map((source, index) => <a key={index} className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700 underline" href={source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={12} /></a>)}</div>{item.evidence.search_entry_point && <iframe title={`Google Search suggestions for ${item.phrase}`} sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={item.evidence.search_entry_point} className="h-28 w-full border-0" />}<div className="flex flex-wrap gap-3">{item.status === 'new' && <button type="button" className={primary} disabled={!canManage || Boolean(busy)} onClick={() => perform('approve', async () => { await keywordRequest(projectId, 'keyword_approve', { id: item.id, recommendation: 'new_article' }); return 'Added to Trend Radar for editorial review.'; })}><Send size={15} />Send to Trend Radar</button>}<button type="button" className={button} disabled={!canManage || Boolean(busy)} onClick={() => perform('status', async () => { await keywordRequest(projectId, item.status === 'dismissed' ? 'keyword_restore' : 'keyword_dismiss', { id: item.id }); return item.status === 'dismissed' ? 'Keyword research restored.' : 'Keyword research dismissed.'; })}>{item.status === 'dismissed' ? <Check size={15} /> : <X size={15} />}{item.status === 'dismissed' ? 'Restore' : 'Dismiss'}</button></div></article>)}</section>}
  </div>;
}
